version: '3'
services:
  ta-vivo-whatsapp-service:
    build: .
    labels:
      - "traefik.http.routers.ta-vivo-whatsapp-service.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.ta-vivo-whatsapp-service.entrypoints=websecure"
      - "traefik.http.routers.ta-vivo-whatsapp-service.tls.certresolver=myresolver"
      - "traefik.http.services.ta-vivo-whatsapp-service.loadbalancer.server.port=${PORT}"
      - "traefik.http.middlewares.ta-vivo-whatsapp-service.ratelimit.average=15"
      - "traefik.http.middlewares.ta-vivo-whatsapp-service.ratelimit.burst=15"
      - "traefik.http.routers.ta-vivo-whatsapp-service.middlewares=ta-vivo-whatsapp-service@docker"
    networks:
      - traefik-network
    
networks:
  traefik-network:
    external:
      name: traefik_proxynet