name: deploy-whatsapp-service

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - master

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  deploy-whatsapp-service:
    # Name the Job
    name: Deploy Ta-vivo WhatsApp service
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    
    steps:
      # Prepare for run tests
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run tests
        run: yarn test
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Connect to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /var/www/services/ta-vivo-whatsapp-service
            git pull
            docker-compose up -d --build
